# Generated by ./update.sh - do not update manually!
# Last updated: 2024-06-26
{
  version = "3.2.9_240617";
  arm64_hash = "sha256-qC3eUc3Hs1nolZJhAds0Qx+tAlD/AR3scGxmcA8dtEw=";
  amd64_hash = "sha256-ofoelAzbuCgxSHsZciWSVkDFDv+zsW+AzZqjeNlaja0=";
}
