# Generated by ./update.sh - do not update manually!
# Last updated: 2025-03-04
{
  version = "3.2.15_250110";
  arm64_hash = "sha256-F2R5j0x2BnD9/kIsiUe+IbZpAKDOQdjxwOENzzb4RJo=";
  amd64_hash = "sha256-hDfaxxXchdZons8Tb5I7bsd7xEjiKpQrJjxyFnz3Y94=";
}
