# Generated by ./update.sh - do not update manually!
# Last updated: 2024-10-03
{
  version = "3.2.12_240927";
  arm64_hash = "sha256-VfM+p2cTNkDZc7sTftfTuRSMKVWwE6TerW25pA1MIR0=";
  amd64_hash = "sha256-xBGSSxXDu+qUwj203i3iAkfI97iLtGOuGMGfEU6kCyQ=";
}
