set mouse=a
set nowrap
set showcmd
set wildmenu
set incsearch
set hlsearch
set termguicolors
set noswapfile
set cursorline
set background=dark
set undodir=~/.cache/vim/undo
set backupdir=~/.cache/vim/backup
set directory=~/.cache/vim/swap
set viewdir=~/.cache/vim/view
set history=2000


map <space> <leader>

augroup vimrc_augroup
    autocmd filetype help nmap q <Cmd>q<CR>
augroup END

colorscheme catppuccin_mocha
noremap ; :
vmap fp "+p

nmap fy <Plug>OSCYankOperator
vmap fy <Plug>OSCYankVisual

map <C-h> 3h
map <C-j> 3j
map <C-k> 3k
map <C-l> 3l

let g:Lf_ShortcutB = 0
let g:Lf_ShortcutF = 0
nmap <leader>ff <Cmd>Leaderf file<CR>
nmap <leader>fo <Cmd>Leaderf mru<CR>
nmap <leader>fw <Cmd>Leaderf rg<CR>
nmap <leader>fb <Cmd>Leaderf buffer<CR>

nmap <leader>bd <Cmd>bd<CR>

let g:lightline = {'colorscheme': 'one'}

let g:Lf_CursorBlink = 0
let g:Lf_WindowPosition = "popup"

let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_exclude_filetypes = ['help', 'coc-explorer']
